from .user_system import UserSystem
from .data_sdm import DataSdm
from .sensor_dimensi import SensorDimensi
from .sensor_lpr import SensorLpr
from .site_info import SiteInfo
from .master_jenis_kendaraan import MasterJenisKendaraan
from .data_penimbangan import DataPenimbangan
from .master_komoditi import MasterKomoditi
from .kategori_komoditi import KategoriKomoditi
from .master_regu import MasterRegu
from .master_shift import MasterShift
from .master_timbangan import MasterTimbangan
from .akses_menu import AksesMenu
from .master_level import MasterLevel
from .lokasi_uppkb import LokasiUppkb
from .instansi import Instansi
from .lokasi_uppkb_pusat import DataLokasiUppkbPusat
from .master_kendaraan import MasterKendaraan
from .data_tilang import DataTilang
from .master_pelanggaran import MasterPelanggaran
from .data_bptd import DataBptd
from .data_provinsi import DataProvinsi
from .data_kab_kota import DataKotaKab
from .master_device import MasterDevice
from .master_sumbu import MasterSumbu
from .master_kategori_kepemilikan import MasterKategoriKepemilikan
from .master_gol_sim import MasterGolSim
from .master_jenis_pelanggaran import MasterJenisPelanggaran
from .data_pelanggaran import DataPelanggaran
from .sanksi import Sanksi
from .pasal import Pasal
from .dokumen import Dokumen
from .sitaan import Sitaan
from .sub_sanksi import SubSanksi
from .pengadilan import Pengadilan
from .kejaksaan import Kejaksaan
from .data_penindakan import DataPenindakan
from .data_sitaan_detail import DataSitaanDetail
from .komoditi_asaltujuan_pengemudi import KomoditiAsalTujuanPengemudi
from .lpr_blue import LprBlue
from .kendaraan_bodong import KendaraanBodong
from .data_peringatan import DataPeringatan
from .master_jenis_kendaraan_tilang import MasterJenisKendaraanTilang