from django.db import models
import uuid

class DataPenimbangan(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    kode_trx = models.CharField(max_length=30)
    kode_uppkb = models.CharField(max_length=30, null=True, blank=True)
    timbangan_id = models.IntegerField(null=True, blank=True)
    # tgl_penimbangan = models.DateTimeField(null=True, blank=True)
    tgl_penimbangan = models.DateTimeField(auto_now_add=True)
    no_kendaraan = models.CharField(max_length=30, null=True, blank=True)
    no_uji = models.CharField(max_length=60, null=True, blank=True)
    tgl_uji = models.DateField(null=True, blank=True)
    tgl_masa_berlaku = models.DateField(null=True, blank=True)
    nama_pemilik = models.CharField(max_length=255, null=True, blank=True)
    alamat_pemilik = models.CharField(max_length=255, null=True, blank=True)
    asal_kota_id = models.IntegerField(null=True, blank=True)
    tujuan_kota_id = models.IntegerField(null=True, blank=True)
    toleransi_komoditi = models.IntegerField(null=True, blank=True)
    toleransi_uppkb = models.IntegerField(null=True, blank=True)
    berat_timbang = models.FloatField(default=0)
    jbi_uji = models.FloatField(default=0)
    kelebihan_berat = models.FloatField(default=0)
    prosen_lebih = models.FloatField(default=0)
    is_gandengan = models.CharField(max_length=1, default='N')
    is_transaksi = models.IntegerField(default=0)  # 0=Penimbangan; 1=Antrian; 2=Lainnya
    nama_pengemudi = models.CharField(max_length=255, null=True, blank=True)
    alamat_pengemudi = models.CharField(max_length=255, null=True, blank=True)
    jenis_kendaraan_id = models.IntegerField(null=True, blank=True)
    gol_sim_id = models.IntegerField(null=True, blank=True)
    is_melanggar = models.CharField(max_length=1, default='N')
    is_active = models.CharField(max_length=1, default='Y')
    gandengan_no_uji = models.CharField(max_length=60, null=True, blank=True)
    gandengan_tgl_uji = models.CharField(max_length=60, null=True, blank=True)
    gandengan_masa_berlaku = models.CharField(max_length=60, null=True, blank=True)
    gandengan_jbi_uji = models.FloatField(default=0)
    gandengan_jbki = models.FloatField(default=0)
    jbb_uji = models.FloatField(default=0)
    jbkb_uji = models.FloatField(default=0)
    mst_uji = models.FloatField(default=0)
    kategori_kepemilikan_id = models.IntegerField(null=True, blank=True)
    foto_depan = models.CharField(max_length=255, null=True, blank=True)
    foto_depan_url = models.CharField(max_length=255, null=True, blank=True)
    foto_belakang = models.CharField(max_length=255, null=True, blank=True)
    foto_belakang_url = models.CharField(max_length=255, null=True, blank=True)
    jenis_kendaraan = models.CharField(max_length=255, null=True, blank=True)
    sumbu = models.CharField(max_length=30, null=True, blank=True)
    sumbu_id = models.IntegerField(null=True, blank=True)
    pemilik_komoditi = models.CharField(max_length=255, null=True, blank=True)
    alamat_pemilik_komoditi = models.CharField(max_length=255, null=True, blank=True)
    no_sim = models.CharField(max_length=30, null=True, blank=True)
    tgl_antrian = models.DateTimeField(auto_now_add=True)
    no_surat_jalan = models.CharField(max_length=60, null=True, blank=True)

    panjang_utama = models.FloatField(default=0)
    panjang_toleransi = models.FloatField(default=0)
    panjang_ukur = models.FloatField(default=0)
    panjang_lebih = models.FloatField(default=0)

    lebar_utama = models.FloatField(default=0)
    lebar_toleransi = models.FloatField(default=0)
    lebar_ukur = models.FloatField(default=0)
    lebar_lebih = models.FloatField(default=0)

    tinggi_utama = models.FloatField(default=0)
    tinggi_toleransi = models.FloatField(default=0)
    tinggi_ukur = models.FloatField(default=0)
    tinggi_lebih = models.FloatField(default=0)

    foh_utama = models.FloatField(default=0)
    foh_toleransi = models.FloatField(default=0)
    foh_ukur = models.FloatField(default=0)
    foh_lebih = models.FloatField(default=0)

    roh_utama = models.FloatField(default=0)
    roh_toleransi = models.FloatField(default=0)
    roh_ukur = models.FloatField(default=0)
    roh_lebih = models.FloatField(default=0)

    asal_kode_kota = models.CharField(max_length=30, null=True, blank=True)
    tujuan_kode_kota = models.CharField(max_length=30, null=True, blank=True)
    device_id = models.IntegerField(null=True, blank=True)
    lokasi_id = models.IntegerField(null=True, blank=True)
    umur_pengemudi = models.IntegerField(null=True, blank=True)
    use_toleransi = models.FloatField(default=0)

    is_surat_tilang = models.CharField(max_length=1, default='N')
    no_ba_tilang = models.CharField(max_length=100, null=True, blank=True)

    petugas_id = models.IntegerField(null=True, blank=True)
    regu_id = models.IntegerField(null=True, blank=True)
    shift_id = models.IntegerField(null=True, blank=True)
    komoditi_id = models.IntegerField(null=True, blank=True)
    kategori_komoditi_id = models.IntegerField(null=True, blank=True)

    is_tindakan = models.CharField(max_length=1, default='N')
    bptd_id = models.IntegerField(null=True, blank=True)
    is_transfer = models.CharField(max_length=1, default='N')
    status_transfer = models.CharField(max_length=1, default='N')
    sync_to_pusat = models.CharField(max_length=1, default='N')
    sync_from_pusat = models.CharField(max_length=1, default='N')
    is_verifikasi = models.CharField(max_length=1, default='N')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    created_by = models.IntegerField(null=True, blank=True)
    updated_by = models.IntegerField(null=True, blank=True)
    deleted_by = models.IntegerField(null=True, blank=True)
    is_deleted = models.CharField(max_length=1, default='N')
    is_send_to_pusat = models.CharField(max_length=1, default='N')
    is_send_to_balai = models.CharField(max_length=1, default='N')

    class Meta:
        db_table = 'jt_penimbangan'